repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        name: GLOBAL check-merge-conflict
      - id: detect-private-key
        name: GLOBAL detect-private-key
      - id: end-of-file-fixer
        name: GLOBAL end-of-file-fixer
      - id: trailing-whitespace
        name: GLOBAL trailing-whitespace

  - repo: local
    hooks:
      # Backend hooks
      - id: ruff-format
        name: BACKEND ruff-format
        entry: cd backend && uv run ruff format
        language: system
        always_run: true
      - id: ruff-lint
        name: BACKEND ruff-lint
        entry: cd backend && uv run ruff check
        language: system
        always_run: true
      - id: mypy
        name: BACKEND mypy
        entry: cd backend && uv run mypy
        language: system
        always_run: true
      - id: pyright
        name: BACKEND pyright
        entry: cd backend && uv run pyright
        language: system
        always_run: true
      - id: pytest
        name: BACKEND pytest
        entry: cd backend && uv run pytest
        language: system
        always_run: true

      # Frontend hooks
      - id: eslint
        name: FRONTEND eslint
        entry: cd frontend && npm run lint
        language: system
        always_run: true
