repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      # Backend hooks
      - id: ruff-format
        name: ruff-format
        entry: cd backend && uv run ruff format
        language: system
        always_run: true
      - id: ruff-lint
        name: ruff-lint
        entry: cd backend && uv run ruff check
        language: system
        always_run: true
      - id: mypy
        name: mypy
        entry: cd backend && uv run mypy
        language: system
        always_run: true
      - id: pyright
        name: pyright
        entry: cd backend && uv run pyright
        language: system
        always_run: true
      - id: pytest
        name: pytest
        entry: cd backend && uv run pytest
        language: system
        always_run: true

      # Frontend hooks
      - id: eslint
        name: eslint
        entry: cd frontend && npm run lint
        language: system
        always_run: true
