[project]
name = "backend"
version = "0.1.0"
description = "The backend for the therobotoverlord project."
readme = "README.md"
authors = [{ name = "Joshua Szepietowski", email = "joshSzep@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
