name: Code Quality Checks

# Define versions at workflow level to avoid duplication
env:
  NODE_VERSION: '23.11.0'
  UV_VERSION: '0.7.8'

on:
  push:
    paths:
      - '**.py'
      - '**.js'
      - '**.ts'
      - '**.jsx'
      - '**.tsx'
      - '**.json'
      - '**.yaml'
      - '**.yml'
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.py'
      - '**.js'
      - '**.ts'
      - '**.jsx'
      - '**.tsx'
      - '**.json'
      - '**.yaml'
      - '**.yml'
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'

# Cancel in-progress runs when a new workflow with the same ref is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Common setup job that other jobs depend on
  setup:
    name: Setup Environment
    # Skip running on PR if already running on push to the same branch
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'backend/.python-version'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install and setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          cache-dependency-glob: 'backend/uv.lock'

  # Global pre-commit checks
  global-checks:
    name: Global Checks
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'backend/.python-version'
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run pre-commit built-in substeps
        run: |
          cd backend
          uv run pre-commit run check-merge-conflict --all-files
          uv run pre-commit run detect-private-key --all-files
          uv run pre-commit run end-of-file-fixer --all-files
          uv run pre-commit run trailing-whitespace --all-files

  # Backend code quality checks (run in parallel)
  ruff-format:
    name: Ruff Format
    needs: setup
    runs-on: ubuntu-latest
    # Only run when Python files change
    if: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'backend') || contains(join(github.event.pull_request.changed_files.*.filename, ' '), '.py') }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'backend/.python-version'
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run Ruff format
        run: cd backend && uv run ruff format --check .

  ruff-check:
    name: Ruff Check
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'backend/.python-version'
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run Ruff check
        run: cd backend && uv run ruff check .

  mypy:
    name: Mypy
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'backend/.python-version'
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run Mypy
        run: cd backend && uv run mypy .

  pyright:
    name: Pyright
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'backend/.python-version'
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run Pyright
        run: cd backend && uv run pyright .

  pytest:
    name: Pytest
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'backend/.python-version'
      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run Pytest
        run: cd backend && uv run pytest

  # Frontend code quality checks
  eslint:
    name: ESLint
    needs: setup
    runs-on: ubuntu-latest
    # Only run when frontend files change
    if: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'frontend') || contains(join(github.event.pull_request.changed_files.*.filename, ' '), '.js') || contains(join(github.event.pull_request.changed_files.*.filename, ' '), '.ts') }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Install dependencies
        run: cd frontend && npm ci
      - name: Run ESLint
        run: cd frontend && npm run lint
